# Generated by Django 3.1.6 on 2021-02-19 14:59

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("accounts", "0002_customer")]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="code",
            field=models.CharField(
                db_index=True,
                default=accounts.models.unique_customer_code,
                max_length=5,
                unique=True,
            ),
        )
    ]
