# Generated by Django 3.1.6 on 2021-02-19 15:01

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [("orders", "0002_orderitem")]

    operations = [
        migrations.RemoveField(model_name="order", name="number"),
        migrations.AddField(
            model_name="order",
            name="code",
            field=models.CharField(
                db_index=True,
                default=orders.models.unique_order_no,
                max_length=7,
            ),
        ),
    ]
